# JDBC connection properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL_SGE}
spring.datasource.username=${DB_USER_SGE}
spring.datasource.password=${DB_PASSWORD_SGE}

server.port=8082

# Dialecto explicito para evitar error de conexion inicial
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
