spring.profiles.active=dev

# JDBC connection properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL_SGE}
spring.datasource.username=${DB_USER_SGE}
spring.datasource.password=${DB_PASSWORD_SGE}
server.port=8082
# Dialecto explicito para evitar error de conexion inicial
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===== JPA Configuration =====
# Desactivar auto-actualizacion de esquema (lo manejara Liquibase)
spring.jpa.hibernate.ddl-auto=validate
# ===== Liquibase Configuration =====
# Habilitar Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
