package com.com4energy.persistence.filerecord.enums;

public enum FailureReason {
    FILE_NOT_FOUND,
    INVALID_FILE_FORMAT,
    INVALID_EXTENSION,
    INVALID_CONTENT_TYPE,
    FILE_TOO_LARGE,
    FILE_IS_EMPTY,
    INVALID_FILENAME,
    PROCESSING_ERROR,
    DUPLICATED_FILE,
    DUPLICATED_FILENAME,
    DUPLICATED_ORIGINAL_FILENAME,
    DUPLICATED_CONTENT,
    UNAUTHORIZED_ACCESS,
    TIMEOUT,
    MAX_RETRIES_EXCEEDED,
    NULL_FILE,
    STORAGE_ERROR,
    UNKNOWN_ERROR,
    STALE_LOCK
}
