-- liquibase formatted sql

-- changeset jesus:RA-012-seed context:dev,qa
-- comment Seed inicial de datos de prueba para incidents
-- precondition-table-exists table:incidents schema:sge

INSERT INTO sge.incidents (
    service_name,
    environment,
    endpoint,
    method_name,
    http_method,
    user_id,
    exception_type,
    message,
    stack_trace,
    category,
    severity,
    error_code,
    filename,
    file_type,
    folder_name,
    status,
    metadata,
    created_by,
    comments,
    resolution,
    closed_by,
    closed_at
) VALUES

      (
          'c4e-files-api',
          'DEV',
          '/upload',
          'processCsv',
          'POST',
          'user123',
          'ValidationException',
          'Columna obligatoria email no encontrada',
          'stack trace ejemplo...',
          'VALIDATION',
          'ERROR',
          'CSV_COLUMN_MISSING',
          'clientes_enero.csv',
          'csv',
          'error',
          'NEW',
          '{"seed": true, "row": 14, "column": "email"}',
          'system',
          'Pendiente de revision por el equipo de integraciones',
          NULL,
          NULL,
          NULL
      ),

      (
          'c4e-files-api',
          'DEV',
          '/upload',
          'processPdf',
          'POST',
          'user456',
          'IOException',
          'No se pudo leer el archivo PDF',
          'stack trace ejemplo...',
          'FILE_PROCESSING',
          'CRITICAL',
          'PDF_READ_ERROR',
          'contrato_marzo.pdf',
          'pdf',
          'error',
          'IN_PROGRESS',
          '{"seed": true, "fileSize": "2MB"}',
          'system',
          'Se esta investigando si el archivo esta corrupto',
          NULL,
          NULL,
          NULL
      ),

      (
          'c4e-payments-api',
          'QA',
          '/process',
          'validatePaymentFile',
          'POST',
          NULL,
          'ValidationWarning',
          'Formato inesperado en columna amount',
          'stack trace ejemplo...',
          'VALIDATION',
          'WARN',
          'CSV_FORMAT_WARNING',
          'pagos_enero.csv',
          'csv',
          'pending',
          'NEW',
          '{"seed": true, "column": "amount"}',
          'system',
          NULL,
          NULL,
          NULL,
          NULL
      ),

      (
          'c4e-files-api',
          'PROD',
          '/upload',
          'processCsv',
          'POST',
          'user999',
          'NullPointerException',
          'Valor nulo inesperado en procesamiento',
          'stack trace ejemplo...',
          'FILE_PROCESSING',
          'ERROR',
          'NULL_VALUE_PROCESSING',
          'clientes_febrero.csv',
          'csv',
          'processed',
          'SOLVED',
          '{"seed": true, "row": 22}',
          'system',
          'Detectado en revision de logs post-despliegue',
          'El valor nulo provenia de un campo opcional no validado. Se añadio validacion en el mapper.',
          'jgonzalez',
          '2026-03-29 18:45:00'
      );

-- rollback DELETE FROM sge.incidents WHERE created_by='system';