FROM maven:3.9.5-eclipse-temurin-21 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -pl c4e-records-api -am -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/c4e-records-api/target/c4e-records-api-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
