# Usamos la imagen oficial de RabbitMQ con gestión web
FROM rabbitmq:3-management

# Configuraciones por defecto
# Puedes configurar usuario y contraseña aquí si quieres, usando variables
# pero por defecto ya vienen como guest/guest
# ENV RABBITMQ_DEFAULT_USER=guest
# ENV RABBITMQ_DEFAULT_PASS=guest
# ENV RABBITMQ_DEFAULT_VHOST=/

# Exponemos los puertos (opcional, porque docker-compose también lo hace)
EXPOSE 5672 15672
