export const FILE_RECORD_STATUS_OPTIONS = [
  'DUPLICATED',
  'DUPLICATED_ORIGINAL_FILENAME',
  'DUPLICATED_CONTENT',
  'FAILED',
  'CRITICAL_VALIDATION_FAILED',
  'REJECTED',
  'PENDING',
  'UPLOADED',
  'ALREADY_EXISTS',
  'CORRUPTED',
  'PROCESSING',
  'SUCCEEDED',
  'RETRY',
  'NEW',
  'DELETED',
  'VALID',
  'VALIDATION_FAILED',
  'NOT_STORED'
] as const;

export const FILE_RECORD_EVENT_STATUS_OPTIONS = [...FILE_RECORD_STATUS_OPTIONS, 'UNKNOWN'] as const;

export const FILE_RECORD_ORIGIN_OPTIONS = ['API', 'MANUAL', 'JOB', 'MAIN_APP', 'UNKNOWN'] as const;

export const FILE_RECORD_TYPE_OPTIONS = [
  'MEDIDA_CCH_F5',
  'MEDIDA_H_P1',
  'MEDIDA_QH_P2',
  'AWAITING_CLASSIFICATION',
  'H_MEASURE',
  'FACTURA',
  'OTRA_FACTURA',
  'DOCUMENTO_PDF',
  'UNKNOWN'
] as const;

export const FILE_RECORD_EVENT_TYPE_OPTIONS = [
  'FILE_REJECTED',
  'FILE_ALREADY_EXISTS',
  'FILE_UPLOADED',
  'FILE_FAILED',
  'FILE_MEASURE_PROCESSED',
  'FILE_PARSE_INCIDENT',
  'FILE_VALIDATION_INCIDENT',
  'FILE_DEFECT_REPORT_CREATED',
  'FILE_PERSISTENCE_QUARANTINE'
] as const;

